name: Readme Discussion

on:
  discussion:
    types: [answered]
    
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest answered discussion
      id: latest_discussion
      uses: peter-evans/github-actions@v3
      with:
        http_method: GET
        url: https://api.github.com/repos/$GITHUB_REPOSITORY/discussions?q=answered&per_page=1
        headers: |
          Accept: application/vnd.github.v3+json
          Authorization: ${{ secrets.TOKEN }}
    - name: Update README with Latest Answered Discussion
      run: |
        question=$(echo ${{ steps.latest_discussion.outputs.data }} | jq -r '.[0].title')
        answer=$(echo ${{ steps.latest_discussion.outputs.data }} | jq -r '.[0].body')
        discussion_url=$(echo ${{ steps.latest_discussion.outputs.data }} | jq -r '.[0].html_url')
        echo -e "\n\n## Latest Answered Discussion\n\n### ${question}\n\n${answer}\n\nDiscussion: ${discussion_url}" >> README.md
