name: Readme Discussion

on:
  discussion:
    types: [answered]
    
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Readme
      uses: peter-evans/readme-pattern@v1.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pattern: '## Latest Discussion(.*)'
        file: 'README.md'
        content: |
          ## Latest Discussion
          ${{ github.event_name }} by ${{ github.actor }} at ${{ github.event.head_commit.timestamp }}

          ${{ github.event.head_commit.message }}

          Discussion: ${{ github.event.repository.html_url }}/discussions/${{ github.event.discussion_number }}
    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README with Latest Discussion"
        git push
